
property:

  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-color-format: 1
  onnx-file: yolov7s-face.onnx
  model-engine-file: yolov7s-face.onnx_b16_gpu0_fp16.engine
  #int8-calib-file=calib.table
  labelfile-path: label_face.txt
  batch-size: 16
  network-mode: 1
  num-detected-classes: 1
  interval: 10
  gie-unique-id: 2
#  operate-on-gie-id: 1
#  operate-on-class-ids: 0
  process-mode: 2
  network-type: 3
  cluster-mode: 4
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  parse-bbox-instance-mask-func-name: NvDsInferParseYoloFace
  custom-lib-path: nvdsinfer_custom_impl_Yolo_face/libnvdsinfer_custom_impl_Yolo_face.so
  output-instance-mask: 1


  pre-cluster-threshold: 0.25
  topk: 300
#  force-implicit-batch-dim: 1
#  batch-size: 16
#  # 0: FP32 and 1=INT8 mode
#  network-mode: 1
#  input-object-min-width: 64
#  input-object-min-height: 64
#  process-mode: 2
#  model-color-format: 1
#  gpu-id: 0
#  gie-unique-id: 2
#  operate-on-gie-id: 1
#  operate-on-class-ids: 0
#  #is-classifier is a legacy config item
#  network-type: 1
#  output-blob-names: predictions/Softmax
#  classifier-async-mode: 1
#  classifier-threshold: 0.51
#  process-mode: 2
  #scaling-filter: 0
  #scaling-compute-hw: 0
